name: Test Local file shared in diff steps

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: save local file
        run: |
          mkdir tmp
          cd tmp
          mkdir -p "${{ github.workspace }}/shared"
          echo "Hello World" > "${{ github.workspace }}/shared/test.txt"

      - name: cat local file
        run: |
          echo "cat file"
          cat "${{ github.workspace }}/shared/test.txt"

