name: Test for actions/fmlint-kt@main
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  kt-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        uses: zdpk/workflows/actions/fmlint-kt@main
