name: Test Label

on: 
  pull_request: 
    types: [opened, reopened, synchronize]
  workflow_dispatch: 

jobs:
  test-label:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Labels
        id: extract
        run: |
          echo "labels=$(jq -r '.pull_request.labels | map(.name) | join(",")' <<< "${{ toJson(github.event) }}")" >> $GITHUB_ENV

      - name: Print Label
        run: echo "Labels are ${{ env.labels }}"