name: Test PR Create Comment

on:
  workflow_dispatch: 

jobs:
  create-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create branches
        run: |
          git switch -c test-base-branch
          git push origin HEAD
          git switch -c test-head-branch
          echo a > a
          git add a
          git commit -m "a"
          git push origin HEAD

  create-pr:
    needs: create-branches
    uses: zdpk/workflows/.github/workflows/create-pr.yml@main


  create-pr-comment:
    needs: create-branches
    secrets: 
      GH_TOKEN: ${{ github.token }}
    uses: zdpk/workflows/.github/workflows/create-pr-comment.yml@main
    with:
      base-branch: test-base-branch
      head-branch: test-head-branch
      title: "test comment"
      description: "test comment body"
      repository: ${{ github.repository }}
