name: Test Label

on: 
  pull_request: 
    types: [opened, reopened, synchronize]
  workflow_dispatch: 

jobs:
  test-label:
    runs-on: ubuntu-latest
    steps:
      - name: Test Extract Label
        id: extract
        run: |
          labels=${{ toJson(github.event.pull_request) }}
          echo "labels: $labels"

      - name: Print Label
        run: echo "Label is ${{ steps.extract.outputs.label }}"