name: double cancel

on: workflow_dispatch

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Double Cancel jobs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "================================================"
          echo "=== gh api /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs --jq '.jobs[]' ==="
          job_ids=$(gh api /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs \
            --jq '.jobs[].id') # -r은 ' '가 아닌 '\n'으로 요소 구분(문자열이 아닌 배열 형태)

          echo "================================================"
          echo "job_ids = $job_ids"
          echo "================================================"

          cancel_url="/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel"
          echo "cancel_url = $cancel_url"

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            $cancel_url

          # for job_id in "$job_ids"; do
          #   echo "job_id = $job_id"
          #   echo "/repos/${{ github.repository }}/actions/jobs/$job_id/cancel"
          #   res=$(gh api -X POST /repos/${{ github.repository }}/actions/jobs/$job_id/cancel)

            # echo ================================
            # echo "res = $res"
            
          # done

  ex1:
    runs-on: ubuntu-latest
    steps:
      - name: Ex1
        run: |
          sleep 50

  ex2:
    runs-on: ubuntu-latest
    steps:
      - name: Ex2
        run: |
          sleep 50

  always:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Always
        run: |
          echo "Always"
          sleep 50
